# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: mariadb
      MARIADB_TCP_PORT: 3306
    ports:
      - "3306:3306"
