spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mariadb
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: true
    user: admin
    password: admin
    schemas: mariadb
    url: jdbc:mysql://localhost:3306/mariadb
    locations: filesystem:db/migration


